name: Deploy master
on:
  push:
    branches:
      - master
#a
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        dotnet-version: 6.0.x
    - name: Run ls command
      run: |
        dir 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --output ./Release
    - name: Run ls command
      run: |
        ls D:\a\Final-Backend-Dotnet\Final-Backend-Dotnet\Release\ 
    - name: Zip artifact for deployment
      run: Compress-Archive -Path D:\a\Final-Backend-Dotnet\Final-Backend-Dotnet\Release\* -Destination Release.zip
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        path: Release.zip
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v1
      with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Eshop
          environment_name: Eshop-env
          version_label: 7.0
          region: us-east-1
          deployment_package: Release.zip
        
