# add synk tool
name: Deploy master
on:
  push:
    branches:
      - master
#ab
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        dotnet-version: 6.0.x
    - name: Run ls command
      run: |
        dir 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore  
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --output ./Release
    - name: Run ls command
      run: |
        ls D:\a\Final-Backend-Dotnet\Final-Backend-Dotnet\Release\ 
    - name: Zip artifact for deployment
      run: Compress-Archive -Path D:\a\Final-Backend-Dotnet\Final-Backend-Dotnet\Release\* -Destination Release.zip
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        path: Release.zip
    - uses: contentful/actions-app-deploy@v1
  with:
    organization-id: ${{ secrets.ORGANIZATION_ID }}
    app-definition-id: ${{ secrets.APP_DEFINITION_ID }}
    access-token: ${{ secrets.ACCESS_TOKEN }}
    folder: build   
    
          environment_name: Eshop-env
          version_label: ${{ github.run_id }}
          region: us-east-1
          deployment_package: Release.zip
        
